Repository bringyourownideas/silverstripe-composer-update-checker, pull requests merged in 2018-06, with the labels that each got.

#31 Upgrading to SS4
  .scrutinizer.yml
  .travis.yml
  _config/extensions.yml
  composer.json
  phpunit.xml.dist
  src/Extensions/CheckComposerUpdatesExtension.php
  src/Extensions/ComposerLoaderExtension.php
  src/Extensions/ComposerUpdateExtension.php
  src/UpdateChecker.php
  tests/Extensions/CheckComposerUpdatesExtensionTest.php
  tests/Extensions/ComposerUpdateExtensionTest.php
  tests/Extensions/ComposerUpdateExtensionTest.yml
  tests/Stubs/ComposerLoaderExtensionStub.php
  tests/UpdateCheckerTest.php
Labels: affects/v4, change/major

#32 DOCS Update readme, includes compatibility and summary of how the module works
  README.md
Labels: affects/v3, type/docs

#35 FIX Ensure that either HOME or COMPOSER_HOME is defined for Composer
  src/Extensions/ComposerLoaderExtension.php
Labels: affects/v3, change/patch
